<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Usuarios.aspx.cs" Inherits="UI.Web.Usuarios1" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style type="text/css">
        .auto-style1 {
            height: 11px;
        }
        .auto-style7 {
            width: 90%;
            height: 273px;
            margin-left: 34px;
            margin-top: 6px;
        }
        .auto-style11 {
            height: 452px;
        }
        .auto-style12 {
            height: 263px;
            text-align: right;
        }
    </style>
</head>
<body style="height: 581px">
    <form id="form1" runat="server" class="auto-style11">
        <div>
            <br />
            </div>
        <table class="auto-style7">
            <tr>
                <td class="auto-style1">Usuarios Existentes</td>
            </tr>
            <tr>
                <td class="auto-style12">
                    <asp:GridView ID="GridViewUsuarios" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="id_usuario" DataSourceID="SqlDataSourceUsuarios" Height="146px" OnSelectedIndexChanged="GridViewUsuarios_SelectedIndexChanged" ShowFooter="True" Width="916px" OnRowCommand="GridViewUsuarios_RowCommand">
                        <Columns>
                            <asp:TemplateField HeaderText="ID" InsertVisible="False" SortExpression="id_usuario">
                                <EditItemTemplate>
                                    <asp:Label ID="Label1" runat="server" Text='<%# Eval("id_usuario") %>'></asp:Label>
                                </EditItemTemplate>
                                <FooterTemplate>
                                    <asp:Button ID="btnInsertar" runat="server" CommandName="Insertar" Text="Insertar" />
                                </FooterTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label1" runat="server" Text='<%# Bind("id_usuario") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Nombre" SortExpression="nombre">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("nombre") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <FooterTemplate>
                                    <asp:TextBox ID="txtBoxNombre" runat="server"></asp:TextBox>
                                </FooterTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label2" runat="server" Text='<%# Bind("nombre") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Apellido" SortExpression="apellido">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox2" runat="server" Text='<%# Bind("apellido") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <FooterTemplate>
                                    <asp:TextBox ID="txtBoxApellido" runat="server"></asp:TextBox>
                                </FooterTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label3" runat="server" Text='<%# Bind("apellido") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Nombre de Usuario" SortExpression="nombre_usuario">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox3" runat="server" Text='<%# Bind("nombre_usuario") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <FooterTemplate>
                                    <asp:TextBox ID="txtBoxNombreUsu" runat="server"></asp:TextBox>
                                </FooterTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label4" runat="server" Text='<%# Bind("nombre_usuario") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Clave" SortExpression="clave">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox4" runat="server" Text='<%# Bind("clave") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <FooterTemplate>
                                    <asp:TextBox ID="txtBoxClave" runat="server"></asp:TextBox>
                                </FooterTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label5" runat="server" Text='<%# Bind("clave") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Habilitado" SortExpression="habilitado">
                                <EditItemTemplate>
                                    <asp:CheckBox ID="CheckBox1" runat="server" Checked='<%# Bind("habilitado") %>' />
                                </EditItemTemplate>
                                <FooterTemplate>
                                    <asp:CheckBox ID="ChkBxHabilitado" runat="server" />
                                </FooterTemplate>
                                <ItemTemplate>
                                    <asp:CheckBox ID="CheckBox1" runat="server" Checked='<%# Bind("habilitado") %>' Enabled="false" />
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Email" SortExpression="email">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox5" runat="server" Text='<%# Bind("email") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <FooterTemplate>
                                    <asp:TextBox ID="TxtBoxEmail" runat="server"></asp:TextBox>
                                </FooterTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label6" runat="server" Text='<%# Bind("email") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                        </Columns>
                    </asp:GridView>
                    <asp:SqlDataSource ID="SqlDataSourceUsuarios" runat="server" ConnectionString="<%$ ConnectionStrings:ConnStringLocal %>" SelectCommand="SELECT * FROM [usuarios]" DeleteCommand="DELETE FROM [usuarios] WHERE [id_usuario] = @id_usuario" InsertCommand="INSERT INTO [usuarios] ([nombre_usuario], [clave], [habilitado], [nombre], [apellido], [email], [cambia_clave], [id_persona]) VALUES (@nombre_usuario, @clave, @habilitado, @nombre, @apellido, @email, @cambia_clave, @id_persona)" UpdateCommand="UPDATE [usuarios] SET [nombre_usuario] = @nombre_usuario, [clave] = @clave, [habilitado] = @habilitado, [nombre] = @nombre, [apellido] = @apellido, [email] = @email, [cambia_clave] = @cambia_clave, [id_persona] = @id_persona WHERE [id_usuario] = @id_usuario">
                        <DeleteParameters>
                            <asp:Parameter Name="id_usuario" Type="Int32" />
                        </DeleteParameters>
                        <InsertParameters>
                            <asp:Parameter Name="nombre_usuario" Type="String" />
                            <asp:Parameter Name="clave" Type="String" />
                            <asp:Parameter Name="habilitado" Type="Boolean" />
                            <asp:Parameter Name="nombre" Type="String" />
                            <asp:Parameter Name="apellido" Type="String" />
                            <asp:Parameter Name="email" Type="String" />
                            <asp:Parameter Name="cambia_clave" Type="Boolean" />
                            <asp:Parameter Name="id_persona" Type="Int32" />
                        </InsertParameters>
                        <UpdateParameters>
                            <asp:Parameter Name="nombre_usuario" Type="String" />
                            <asp:Parameter Name="clave" Type="String" />
                            <asp:Parameter Name="habilitado" Type="Boolean" />
                            <asp:Parameter Name="nombre" Type="String" />
                            <asp:Parameter Name="apellido" Type="String" />
                            <asp:Parameter Name="email" Type="String" />
                            <asp:Parameter Name="cambia_clave" Type="Boolean" />
                            <asp:Parameter Name="id_persona" Type="Int32" />
                            <asp:Parameter Name="id_usuario" Type="Int32" />
                        </UpdateParameters>
                    </asp:SqlDataSource>
                    <asp:Button ID="btnSalir" runat="server" OnClick="btnSalir_Click" Text="Salir" />
                </td>
            </tr>
        </table>
    </form>
</body>
</html>
