<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Usuarios.aspx.cs" Inherits="UI.Web.Usuarios1" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style type="text/css">
        .auto-style1 {
            height: 11px;
        }
        .auto-style7 {
            width: 90%;
            height: 273px;
            margin-left: 34px;
            margin-top: 6px;
        }
        .auto-style11 {
            height: 452px;
        }
        .auto-style12 {
            height: 263px;
            text-align: right;
        }
        .auto-style13 {
            height: 27px;
            text-align: left;
        }
        .auto-style15 {
            margin-left: 6px;
        }
    </style>
</head>
<body style="height: 581px">
    <form id="form1" runat="server" class="auto-style11">
        <div>
            <br />
            </div>
        <table class="auto-style7">
            <tr>
                <td class="auto-style1">Usuarios Existentes</td>
            </tr>
            <tr>
                <td class="auto-style13">
                    <asp:Button ID="BtnNuevo" runat="server" OnClick="BtnNuevo_Click" Text="Nuevo" />
                    <asp:Button ID="BtnEditar" runat="server" CssClass="auto-style15" OnClick="BtnEditar_Click" Text="Editar" />
                </td>
            </tr>
            <tr>
                <td class="auto-style12">
                    <asp:GridView ID="GridViewUsuarios" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" DataKeyNames="id_usuario" DataSourceID="SqlDataSourceUsuarios" Height="146px" OnSelectedIndexChanged="GridViewUsuarios_SelectedIndexChanged" Width="1114px" AutoGenerateSelectButton="True" OnRowCommand="GridViewUsuarios_RowCommand" OnRowUpdating="GridViewUsuarios_RowUpdating">
                        <Columns>
                            <asp:BoundField DataField="id_usuario" HeaderText="ID" InsertVisible="False" ReadOnly="True" SortExpression="id_usuario" />
                            <asp:BoundField DataField="nombre_usuario" HeaderText="Nombre de Usuario" SortExpression="nombre_usuario" />
                            <asp:BoundField DataField="clave" HeaderText="Clave" SortExpression="clave" />
                            <asp:CheckBoxField DataField="habilitado" HeaderText="Habilitado" SortExpression="habilitado" />
                            <asp:BoundField DataField="nombre" HeaderText="Nombre" SortExpression="nombre" />
                            <asp:BoundField DataField="apellido" HeaderText="Apellido" SortExpression="apellido" />
                            <asp:BoundField DataField="email" HeaderText="Email" SortExpression="email" />
                        </Columns>
                    </asp:GridView>
                    <asp:SqlDataSource ID="SqlDataSourceUsuarios" runat="server" ConnectionString="<%$ ConnectionStrings:ConnStringLocal %>" SelectCommand="SELECT * FROM [usuarios]" DeleteCommand="DELETE FROM [usuarios] WHERE [id_usuario] = @id_usuario" InsertCommand="INSERT INTO [usuarios] ([nombre_usuario], [clave], [habilitado], [nombre], [apellido], [email], [cambia_clave], [id_persona]) VALUES (@nombre_usuario, @clave, @habilitado, @nombre, @apellido, @email, @cambia_clave, @id_persona)" UpdateCommand="UPDATE [usuarios] SET [nombre_usuario] = @nombre_usuario, [clave] = @clave, [habilitado] = @habilitado, [nombre] = @nombre, [apellido] = @apellido, [email] = @email, [cambia_clave] = @cambia_clave, [id_persona] = @id_persona WHERE [id_usuario] = @id_usuario">
                        <DeleteParameters>
                            <asp:Parameter Name="id_usuario" Type="Int32" />
                        </DeleteParameters>
                        <InsertParameters>
                            <asp:Parameter Name="nombre_usuario" Type="String" />
                            <asp:Parameter Name="clave" Type="String" />
                            <asp:Parameter Name="habilitado" Type="Boolean" />
                            <asp:Parameter Name="nombre" Type="String" />
                            <asp:Parameter Name="apellido" Type="String" />
                            <asp:Parameter Name="email" Type="String" />
                            <asp:Parameter Name="cambia_clave" Type="Boolean" />
                            <asp:Parameter Name="id_persona" Type="Int32" />
                        </InsertParameters>
                        <UpdateParameters>
                            <asp:Parameter Name="nombre_usuario" Type="String" />
                            <asp:Parameter Name="clave" Type="String" />
                            <asp:Parameter Name="habilitado" Type="Boolean" />
                            <asp:Parameter Name="nombre" Type="String" />
                            <asp:Parameter Name="apellido" Type="String" />
                            <asp:Parameter Name="email" Type="String" />
                            <asp:Parameter Name="cambia_clave" Type="Boolean" />
                            <asp:Parameter Name="id_persona" Type="Int32" />
                            <asp:Parameter Name="id_usuario" Type="Int32" />
                        </UpdateParameters>
                    </asp:SqlDataSource>
                    <asp:Button ID="btnSalir" runat="server" OnClick="btnSalir_Click" Text="Salir" />
                </td>
            </tr>
        </table>
    </form>
</body>
</html>
